// Note #1: running at 240MHz, there are exactly 240 cycles in 1us
// Note #2: according to ARM specs, NOP may be optimized out to 0 cycles. so we use MOV instead

void sleep_us_cm4(int numMicroSeconds)
{
	asm("WAIT_1_US:\n\t"
		"MOV     R0, R0\n\t"     // clock cycle 1
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"      // clock cycle 10
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"      // clock cycle 20
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"      // clock cycle 30
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"      // clock cycle 40
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"      // clock cycle 50
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"      // clock cycle 60
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"      // clock cycle 70
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"      // clock cycle 80
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"      // clock cycle 90
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"      // clock cycle 100
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"      // clock cycle 110
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"      // clock cycle 120
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"      // clock cycle 130
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"      // clock cycle 140
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"      // clock cycle 150
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"      // clock cycle 160
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"      // clock cycle 170
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"      // clock cycle 180
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"      // clock cycle 190
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"      // clock cycle 200
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"      // clock cycle 210
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"      // clock cycle 220
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"      // clock cycle 230
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"
		"MOV     R0, R0\n\t"      // clock cycle 238
		"SUBS    %[value], %[value], #1\n\t"      // clock cycle 239
		"BGT     WAIT_1_US\n\t"       // clock cycle 240
		"BX      LR"
		 : [value] "+r" (numMicroSeconds));      // return
}
